version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:10.1.0-1.73.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create directory"
          command: mkdir /Ishiko-cpp && echo 'export ISHIKO_CPP="/Ishiko-cpp"' >> $BASH_ENV
      - run:
          name: "Checkout Ishiko-cpp/Platform dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Platform.git
      - run:
          name: "Checkout Ishiko-cpp/Errors dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Errors.git
      - run:
          name: "Checkout Ishiko-cpp/Text dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Text.git
      - checkout:
          path: /Ishiko-cpp/Process
      - run:
          name: "Build Ishiko-cpp/Platform dependency"
          command: cd /Ishiko-cpp/Platform/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Errors dependency"
          command: cd /Ishiko-cpp/Errors/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Text dependency"
          command: cd /Ishiko-cpp/Text/Makefiles/GNUmakefile && make
      - run:
          name: Build
          command: cd /Ishiko-cpp/Process/Makefiles/GNUmakefile && make
      - run:
          name: "Checkout Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/TestFramework.git
      - run:
          name: "Build Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp/TestFramework/Core/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /Ishiko-cpp/Process/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Build ExitCodeTestHelper
          command: cd /Ishiko-cpp/Process/Tests/ExitCodeTestHelper/Makefiles/GNUmakefile && make
      - run:
          name: Build StandardOutputTestHelper
          command: cd /Ishiko-cpp/Process/Tests/StandardOutputTestHelper/Makefiles/GNUmakefile && make
      - run:
          name: Build DumpTestHelper
          command: cd /Ishiko-cpp/Process/Tests/DumpTestHelper/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /Ishiko-cpp/Process/Tests/Makefiles/GNUmakefile && ./IshikoProcessTests
